version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pokescan-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokescan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: pokescan-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pokescan
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  prisma-studio:
    build: .
    container_name: pokescan-prisma-studio
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/pokescan
    ports:
      # Mapeamento da porta 5555
      - "5555:5555" 
    volumes:
      - .:/app
    command: ["npx", "prisma", "studio", "--port", "5555", "--browser", "none"]
    restart: "no"

volumes:
  postgres_data:
